### ISSUE TITLE
error: "call to undefined method OpenAI::chat() "

### ISSUE THREAD

**Issue by projectwehelp** [theokafadaris/chatwire#1]
Hi, 

Fresh setup, after fixing he ChatBoxController name issue (changed it to ChatBoxController, to make it work, as it was referenced in routes/web.php ) ,now getting this error: "call to undefined method OpenAI::chat() "

What am i missing?

Thank you!

**Comment by theokafadaris** [comment]
Hello!
As far as the ChatBoxController, you are right, I pushed a correction.
Can you give me a a screenshot with the error of undefined method?
Can you check in your composer.json that `openai-php/laravel` is installed?
Have you followed all the steps from here?
https://github.com/theokafadaris/chatwire#getting-started

Thank you,
Theodoros

**Comment by projectwehelp** [comment]
Thanks for the quick response!

#1 i checked with composer show and openai-php/laravel is installed 
nikic/php-parser                   v4.15.4  A PHP parser written in PHP
nunomaduro/collision               v7.4.0   Cli error handling for console/command-line PHP applicati...
nunomaduro/termwind                v1.15.1  Its like Tailwind CSS, but for the console.
openai-php/client                  v0.4.2   OpenAI PHP is a supercharged PHP API client that allows y...
openai-php/laravel                 v0.4.2   OpenAI PHP for Laravel is a supercharged PHP API client t...

checked composer.json for openai-php/laravel  : 

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "jantinnerezo/livewire-alert": "^2.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "league/commonmark": "^2.3",
        "livewire/livewire": "^2.12",
        "openai-php/laravel": "^0.4.0"
    },

#2 the error message on storage/logs is: 


[2023-04-12 08:40:44] local.ERROR: Call to undefined method OpenAI::chat() {"userId":1,"exception":"[object] (Error(code: 0): Call to undefined method OpenAI::chat() at /var/www/vhosts/xxxx/chatwire/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:353)
[stacktrace]
#0 /var/www/vhosts/xxxx/chatwire/app/Http/Livewire/ChatBox.php(58): Illuminate\\Support\\Facades\\Facade::__callStatic()
#1 /var/www/vhosts/xxxxx/chatwire/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\ChatBox->ask()
#2 /var/www/vhosts/xxxx/chatwire/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/vhosts/xxxxxx/chatwire/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()

Here are the screenshots:
#4 The error screen 
<img width="1278" alt="Screenshot 2023-04-13 at 7 47 06 AM" src="https://user-images.githubusercontent.com/78574989/231610849-95ccf4d1-5ee6-40ef-9e9e-a4b4c25d7787.png">

#3 the screen before the error strike
<img width="1274" alt="Screenshot 2023-04-13 at 7 46 46 AM" src="https://user-images.githubusercontent.com/78574989/231610898-8bc669a5-95e3-4aed-a125-7622bf875122.png">

And yes, i followed the steps and even sort of fixed the ChatBoxController spello , it works till i hit send , Thank you

**Comment by projectwehelp** [comment]
FYI .. I just changed the code on line #58 in  . .. Livewire/ChatBox.php to use the non facades way to initialize the OpenAI client and it is working now: :

$yourApiKey = getenv('OPENAI_API_KEY');
$client = OpenAI::client($yourApiKey);
//$response = OpenAI::chat()->create([ 
$response = $client->chat()->create([   

Wonder what was wrong in the earlier approach?

**Comment by theokafadaris** [comment]
That is great! But I cannot understand what can be the problem.
I followed exactly the instructions of the relevant package from here and it works without problem!
https://github.com/openai-php/laravel#get-started

**Comment by theokafadaris** [comment]
I checked once more and I faced the same problem with you.
I pushed an update to fix this. You can pull the new code because I changed a little bit some functions in the controllers.
Please let me know if after the new code everything is working as expected!

Thank you!
Theodoros

**Comment by projectwehelp** [comment]
I just browsed  the code here ( haven't tried it yet, as my modified version is working fine) I seen that T you are also moved to the standard openai-php call for ask().

What is the wordpress controller for? The dashboard chat listing?

Will try it out in some time

**Comment by projectwehelp** [comment]
Additionally openai api call caching will be a good thing to add

**Comment by theokafadaris** [comment]
As I told you, I faced also the issue you reported so I changed the approach as you proposed.
As far as wordpress controller, it will be my new addition in chatwire. My idea is to ask from a wordpress blog all the posts and chatgpt to propose the best SEO keyword for them. So this is my preparation in this direction.

**Comment by projectwehelp** [comment]
Setup  your updated repo, getting a similar error:

[2023-04-13 23:38:40] local.ERROR: Call to undefined method OpenAI\Client::client() {"userId":1,"exception":"[object] (Error(code: 0): Call to undefined method OpenAI\\Client::client() at /var/www/vhosts/xxxxxx/chatwire/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:353)
[stacktrace]
#0 /var/www/vhosts/xxxxxx/chatwire/app/Models/ChatBox.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic()
#1 /var/www/vhosts/xxxxxxx/chatwire/app/Http/Livewire/ChatBox.php(53): App\\Models\\ChatBox::ask()
#2 /var/www/vhosts/xxxxxxx/chatwire/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\ChatBox->ask()


Will check this in parallel, looks like some missing  namespace declaration issue?

**Comment by theokafadaris** [comment]
It seems that the openai-laravel package (https://github.com/openai-php/laravel) made some changes (https://github.com/openai-php/laravel/commit/c40ac21d5e5908b10ed370ac2a2b7d7b16978361) the previous days.
I corrected again so please again to pull the latest changes. 
In order to avoid such problems, I changed the instructions for installation from `composer update` to `composer install`.

**Comment by projectwehelp** [comment]
Your new update, works perfectly. I pulled it and it worked right out on first click!

Well done ! 

Thank you !
